### ISSUE TITLE
The recurrence interval

### ISSUE THREAD

**Issue by verasbr** [ATVWGS/tenant-management-framework#16]
https://github.com/ATVWGS/tenant-management-framework/blob/73cd30df2779c6bd1956da023d59981739c8fabc/TMF/internal/functions/validate/Validate-AssignmentReviewSettings.ps1#L6

Validation set should be expanded to include all possible values:
 onetime, weekly, monthly, quarterly, halfyearly, annual

**Comment by verasbr** [comment]
PR create to resolve this 
https://github.com/ATVWGS/tenant-management-framework/pull/17

**Comment by ATVWGS** [comment]
@verasbr: Added additional recurrenceTypes in prepare-release/v1.6 branch
