### ISSUE TITLE
Access Package Application resource error when using prepare-release/v1.6

### ISSUE THREAD

**Issue by verasbr** [ATVWGS/tenant-management-framework#19]
Seeing the following error when running a TMF test on a config that requires an application resource to be onboarded to an access package. The Application does exist so not sure why its getting this. 
![image](https://user-images.githubusercontent.com/48932313/193509857-6c007a39-3477-476a-94cc-3f01cc4265d6.png)

If I onboarded to an access package via the portal and then run the config it adds the resource to the access package but that defeats the purpose of using TMF
![image](https://user-images.githubusercontent.com/48932313/193510356-c9767c66-6641-4549-a342-254c08cc6719.png)

**Comment by ATVWGS** [comment]
Can you share the configuration for the access package containing "dummy app 3"?

**Comment by verasbr** [comment]
@ATVWGS apologies for the delayed response my nonfictions were going to the wrong email. 
[accessPackages.txt](https://github.com/ATVWGS/tenant-management-framework/files/9826055/accessPackages.txt)

**Comment by ATVWGS** [comment]
@verasbr I recently pushed a new version of prepare-release/v1.6 where the error should be fixed. The problem was that during Test-TmfAccessPackage there was no "-SearchInDesiredConfiguration" switch. Please test the new release and let me know if the error is fixed.

**Comment by verasbr** [comment]
@ATVWGS Testing and now I see the error on the Test phase but shouldn't it be seeing that there is a create job for the AP resource and not fail? 
![image](https://user-images.githubusercontent.com/48932313/198027810-1bd80959-5187-483d-8860-84320c2f2e9f.png)

**Comment by ATVWGS** [comment]
@verasbr I found the issue. The TMF internal displayname accessPackageResources is concatenated as followed:
    "Catalog name - application name"
to be unique in the configuration and to be able to use the same resource in different catalogs.

In the function "Resolve-AccessPackageResource" for searching in the desired configuration this wasn't respected, so the search didn't find the resource. This has been fixed and also tested in the latest version of prepare-release/v1.6.

Please give feedback if now everything is working as expected.

**Comment by verasbr** [comment]
@ATVWGS Can confirm now working as expected for test phase and invoke phase. Thanks for looking into it.
