### ISSUE TITLE
AccessPackage validation in line with Graph APIs

### ISSUE THREAD

**Issue by ar11906** [ATVWGS/tenant-management-framework#22]
## Summary

The current argument validations for access packages are not in line with the MSGraph APIs.
For instance, `AllowedTargetScope` value of `notSpecified` is not accepted by TMF but is a valid value according to the API specification.

https://learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0

**Comment by ATVWGS** [comment]
@ar11906 Input was added in the latest prepare-release/v1.7
