### ISSUE TITLE
Setup of collaboration channels

### ISSUE THREAD

**Issue by salty2011** [ATVWGS/tenant-management-framework#4]
Apologies @johannesvwgs  if this is the wrong approach but was keen to reach out and see about getting either a Slack / Discord going that the community could join to discuss and collaborate on this further.

I myself would be keen to contribute more.

**Comment by johannesvwgs** [comment]
Hi @salty2011, I've enabled Discussions feature for the repo. Should work for now. We can think of something else in the future.
