### ISSUE TITLE
Missing dependency for Microsoft.Graph

### ISSUE THREAD

**Issue by salty2011** [ATVWGS/tenant-management-framework#5]
Currently the module will successfully load even if you are missing the Microsoft.Graph module.

Most commands still work until the Invoke-TMF commands are used. Interestingly the Invoke-TmfAccessPackageCatalog does not output anything, not even an error, where-as the Invoke-TmfGroup will error out hinting that the Mocrosoft.Graph module is missing

**Comment by salty2011** [comment]
Looking at the Invoke-TmfAccessPackageCatalog , lines 27 and 30 the test is

`$testResults = Test-TmfAccessPackage -SpecificResources $SpecificResources -Cmdlet $Cmdlet`

Correcting to 

`$testResults = Test-TmfAccessPackageCatalog -SpecificResources $SpecificResources -Cmdlet $Cmdlet`

This appears correct the issue

**Comment by salty2011** [comment]
Reading through the Graph SDK found the module to load would be 'Microsoft.Graph.Identity.Governance" , think that covers off everything

This fix is included in PR #8

**Comment by johannesvwgs** [comment]
Fixed in the next preview build. Currently running.
