### ISSUE TITLE
 Invoke-TmfAccessPackageCatalog does not create resources

### ISSUE THREAD

**Issue by salty2011** [ATVWGS/tenant-management-framework#7]
When using Invoke-TmfAccessPackageCatalog results in no resources getting created. This appears to be due to lines 27 and 30 in that function using the  Test-TmfAccessPackage function instead of  Test-TmfAccessPackageCatalog.

This is to address issue #7

**Comment by johannesvwgs** [comment]
I'm working on it. :)

**Comment by salty2011** [comment]
@johannesvwgs  I have the fixes present, happy to submit the PR

**Comment by johannesvwgs** [comment]
@salty2011 Thanks for your PR! I already merged in on our side. Fix is now in the v1.4 branch. Build for the preview version currently running.

Feel free to create pull requests to the prepare-release branches in the future!
