### ISSUE TITLE
Access Package Policies - Ability to rename a policy

### ISSUE THREAD

**Issue by verasbr** [ATVWGS/tenant-management-framework#9]
Currently if a Access Package Policy is renamed in a json file it doesn't rename it on the Access Package it creates a new policy, keeping the existing AP Policy, would be nice if it could rename the existing access policy.
Below is an example of "Initial Policy" being renamed in the config but a new policy is crated. 
![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/48932313/161466449-fb3f3d44-d9ac-4a7d-8811-e09d97577992.png)
![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/48932313/161466464-fdbe2523-f5ec-4bb9-8acd-05fbaaec1c2d.png)
.

**Comment by johannesvwgs** [comment]
I've created an internal feature request.

**Comment by ATVWGS** [comment]
Renaming of accessPackageAssignmentPolicies is possible in the latest version (1.5.493) by adding a string array "oldNames" which holds the oldName(s) of the object.
